### PR TITLE
Added email notification feature via `episoder notify`.

### PR DESCRIPTION
**Pull request by chrisspen**

### CODE REVIEW

**Comment by chrisspen** [comment]
Note, this required a schema change, with the addition of a new date field. It looks like the schema-change tracking mechanism you use simply drops the database and recreates it from scratch. That doesn't seem ideal, but since I'm not too familiar with Sqlalchemy, I kept it as-is. Let me know if there's a better way.

**Comment by cockroach** [comment]
Hey

Sorry for taking so long to respond and thanks a lot, this looks very useful; I'll make sure to add it to the next release. And you are right, the database schema update mechanism is a bit of a mess, I'll have to see whether I can do this better now that there is an actual, proper schema change to be made.

**Comment by chrisspen** [comment]
I cleaned up the code and added a testing harness for Travis-CI.

e.g. https://travis-ci.org/chrisspen/episoder

**Comment by cockroach** [comment]
The delay is quite embarrassing, sorry, I should get this merged soon now.

**Comment by cockroach** [comment]
With the recent changes to episoder I had to rewrite this quite a bit so I won't be able to merge this pull request directly.

On the positive side the only difference visible to the user should be that I chose to use two values (email_to and email_user) instead of just one; depending on your email provider these might differ.

Great work though and sorry it took me so long to merge it.

**Comment by chrisspen** [comment]
Ok, thanks for reviewing it. I'll update my PR once the development branch is merged into master.

**Pull request closed without merging**
